# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# Define a job to be invoked later in a workflow.
jobs:
  lint-dockerfile:
    working_directory: ~/karsajobs
    docker:
      - image: hadolint/hadolint
    steps:
      - checkout
      - run:
          name: Lint karsajobs Dockerfile with hadolint
          command: hadolint ~/karsajobs/Dockerfile
  test-app:
    working_directory: ~/karsajobs
    docker:
      # pull circleci's "convenience image" to test + later build
      # matched go version with one mentioned in karsajobs' Dockerfile
      - image: cimg/go:1.15
    steps:
      - checkout
      - run:
          name: Run karsajobs backend unit store_test_results
          command: go test -v -short --count=1 $(go list ./...)
  build-app-karsajobs:
    working_directory: ~/karsajobs
    docker:
      - image: cimg/go:1.15
    steps:
      - checkout
      - run:
          name: Build and push image to GHCR
          command: |
            chmod +x ./build_push_image_karsajobs.sh
            bash ./build_push_image_karsajobs.sh
  

# Invoke jobs via workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  karsajobs:
    jobs:
      - lint-dockerfile:
          filters:
            branches:
              only: karsajobs
      - test-app:
          filters:
            branches:
              only: karsajobs
      - build-app-karsajobs:
          filters:
            branches:
              only: karsajobs
